from solardatatools.algorithms.capacity_change import CapacityChange
from solardatatools.algorithms.time_shifts import TimeShift
from solardatatools.algorithms.sunrise_sunset_estimation import SunriseSunset
from solardatatools.algorithms.soiling import soiling_seperation
from solardatatools.algorithms.clipping import ClippingDetection