from solardatatools.algorithms.capacity_change import CapacityChange
from solardatatools.algorithms.time_shifts import TimeShift
from solardatatools.algorithms.sunrise_sunset_estimation import SunriseSunset