{% set name = "solar-data-tools" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  git_url: https://github.com/slacgismo/solar-data-tools

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - scipy
    - numpy >=1.22
    - pandas
    - seaborn
    - requests

  run:
    - scipy
    - numpy >=1.22
    - pandas
    - seaborn
    - requests
    - scikit-learn
    - pvlib
    - cvxpy
    - pv-system-profiler

about:
  home: https://github.com/bmeyers/solar-data-tools
  license: BSD
  license_family: BSD
  license_file:
  summary: Tools for performing common tasks on solar PV data signals
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - bmeyers
    - derins
